In [1]:
import numpy as np

#### Criação de vetores e matrizes

Há várias formas para criar vetores, uma delas é usando a função *array*. 
O tipo dos dados é deduzido a partir do tipo dos elementos inseridos.

In [2]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [3]:
a.shape

(3,)

In [4]:
a.ndim

1

In [5]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

Erro frequente: usar múltiplos argumentos no lugar de usar uma lista de números.

In [6]:
a = np.array(1,2,3,4)    # errado

ValueError: only 2 non-keyword arguments accepted

In [7]:
a = np.array([1,2,3,4])  # correto
a

array([1, 2, 3, 4])

A função *array* transforma sequência de sequências em vetores bidimensionais.

In [8]:
# sequência de sequência = matriz
B = np.array([[1.5,2,3], [4,5,6]])
B

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

O tipo dos dados pode ser definido no momento da criação do vetor:

In [9]:
C = np.array([[1,2], [3,4]], dtype=complex)
C

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [10]:
# matriz de zeros
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
# matriz de 1s do tipo inteiro
np.ones((2, 3), dtype=np.int16)                # dtype can also be specified

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [12]:
# matriz identidade
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [13]:
# valores quaisquer
np.empty((2, 3))         

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [14]:
# vetor a partir de uma sequência
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# sequências - início, fim, passo
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [16]:
# sequência - com reais
np.arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [17]:
# com reais é melhor usar
from numpy import pi
np.linspace(0, 2, 9)  # início, fim, n. elementos

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [18]:
# matriz a partir de uma sequência
A = np.arange(15).reshape(3, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
A.shape

(3, 5)

In [20]:
A.ndim

2

In [21]:
A.dtype.name

'int64'

In [22]:
A.size

15

In [23]:
type(A)

numpy.ndarray

In [24]:
X = np.linspace(0, 2 * pi, 10)
X

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

In [25]:
F = np.sin(X)
F

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])

### Mostrar vetores e matrizes

In [26]:
a = np.arange(6)                         # vetor
a

array([0, 1, 2, 3, 4, 5])

In [27]:
print(a)

[0 1 2 3 4 5]


In [28]:
A = np.arange(12).reshape(4,3)           # matriz
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### Operações elementares

#### Soma de vetores

In [30]:
a = np.arange(3)
print(a)

[0 1 2]


In [31]:
b = np.array([2, 5, 6])
print(b)

[2 5 6]


In [32]:
s = a + b

In [33]:
print(s)

[2 6 8]


In [34]:
s.shape

(3,)

In [35]:
c = np.array([[2, 4, 5]])
c

array([[2, 4, 5]])

In [36]:
c.shape

(1, 3)

In [37]:
a + c

array([[2, 5, 7]])

In [38]:
a - c

array([[-2, -3, -3]])

#### Soma de matrizes

In [39]:
A = np.arange(6).reshape(2,3)           # matriz
A

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
B = np.array([[1.5,2,3.4], [4,5,6]])
B

array([[ 1.5,  2. ,  3.4],
       [ 4. ,  5. ,  6. ]])

In [41]:
A + B

array([[  1.5,   3. ,   5.4],
       [  7. ,   9. ,  11. ]])

#### Multiplicação por escalar

In [42]:
2 * A

array([[ 0,  2,  4],
       [ 6,  8, 10]])

#### Produto de Hadamard

In [43]:
A * B

array([[  0. ,   2. ,   6.8],
       [ 12. ,  20. ,  30. ]])

### Operações com matrizes

In [44]:
E = np.array([[2, 4, 5], [1, 0, 3]])
E

array([[2, 4, 5],
       [1, 0, 3]])

In [45]:
E.shape

(2, 3)

In [46]:
F = np.array([[4, 5], [1, 3], [-1, 1]])
F

array([[ 4,  5],
       [ 1,  3],
       [-1,  1]])

In [47]:
F.shape

(3, 2)

#### Multiplicação de matrizes

In [48]:
E @ F

array([[ 7, 27],
       [ 1,  8]])

#### Transposta

In [49]:
E.T

array([[2, 1],
       [4, 0],
       [5, 3]])

In [50]:
E.T @ E

array([[ 5,  8, 13],
       [ 8, 16, 20],
       [13, 20, 34]])

#### Posto de uma matriz

In [51]:
np.linalg.matrix_rank(E)

2

In [52]:
G = np.array([[7, 13, 1, 12], [20, 3, 14, 7], [4, 15, 4, 2], [4, 18, 1, 1]])
G

array([[ 7, 13,  1, 12],
       [20,  3, 14,  7],
       [ 4, 15,  4,  2],
       [ 4, 18,  1,  1]])

In [53]:
np.linalg.matrix_rank(G)

4

#### Determinante de uma matriz

In [54]:
np.linalg.det(G)

10058.999999999993

In [55]:
A = np.array([[1, 2, 3], [4, 5, 4], [3, 2, 1]])
A

array([[1, 2, 3],
       [4, 5, 4],
       [3, 2, 1]])

#### Traço de uma matriz

In [56]:
# traço
np.trace(A)

7

#### Inversa clássica

In [57]:
A1 = np.linalg.inv(A)
A1

array([[ 0.375, -0.5  ,  0.875],
       [-1.   ,  1.   , -1.   ],
       [ 0.875, -0.5  ,  0.375]])

#### Inversa generalizada

In [58]:
Am = np.linalg.pinv(A)
Am

array([[ 0.375, -0.5  ,  0.875],
       [-1.   ,  1.   , -1.   ],
       [ 0.875, -0.5  ,  0.375]])

Exercício: testar se $\boldsymbol{A}^{-1}\boldsymbol{A} = \boldsymbol{A}\boldsymbol{A}^{-1} = \boldsymbol{I}$

In [59]:
A @ A1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [60]:
A1 @ A

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Exercício: testar se $\boldsymbol{A}\boldsymbol{A}^{+}\boldsymbol{A} = \boldsymbol{A}$ e $\boldsymbol{A}^{+}\boldsymbol{A}\boldsymbol{A}^{+} = \boldsymbol{A}^{+}$

In [61]:
 A @ Am @ A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  4.],
       [ 3.,  2.,  1.]])

In [62]:
Am @ A @ Am

array([[ 0.375, -0.5  ,  0.875],
       [-1.   ,  1.   , -1.   ],
       [ 0.875, -0.5  ,  0.375]])

In [63]:
# matriz com números aleatórios
A = np.random.randn(3, 3)
Ai = np.linalg.pinv(A)

In [64]:
print(A)

[[-0.22218579  1.90517539  1.42904873]
 [-1.06588242  0.62295283  0.60476298]
 [ 1.07689985 -0.02087491  0.19587456]]


In [65]:
print(Ai)

[[ 0.19750342 -0.59114857  0.38423961]
 [ 1.26155828 -2.32122885 -2.0371966 ]
 [-0.95140725  3.00269904  2.7756852 ]]


In [66]:
np.allclose(A, A @ Ai @ A)

True

In [67]:
np.allclose(Ai, Ai @ A @ Ai)

True

#### Decomposição espectral: autovalores e autovetores

In [68]:
S = np.array([[8, -2], [-2, 5]])
l, e = np.linalg.eig(S)
print(l)
print(e)

[ 9.  4.]
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]


#### Matriz $\boldsymbol{\Lambda}$

In [69]:
L = np.diag(l)
L

array([[ 9.,  0.],
       [ 0.,  4.]])

#### Autovalores ordenados em ordem descrescente

In [72]:
# uma matriz S
S = np.array([[8, -2], [-2, 5]])

In [73]:
# l: autovalores
# e: autovetores
l, e = np.linalg.eig(S)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:,idx]
print(l)
print(e)

[ 9.  4.]
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]


In [74]:
L.shape

(2, 2)

In [75]:
# matriz P
P = e
P

array([[ 0.89442719,  0.4472136 ],
       [-0.4472136 ,  0.89442719]])

In [76]:
# PLP' = A
P @ L @ P.T

array([[ 8., -2.],
       [-2.,  5.]])

In [77]:
# verificar lambda = P'AP   e   A = P lambda P' (usar round)
# verificar que os determinantes de A e lambda são iguais
# verificar que traços são iguais
# solução de sistema de equações

#### Outras decomposições de matrizes

In [78]:
A = np.array([[4, -1, 1], [4, 5, 3], [-2, 0, 0]])
A

array([[ 4, -1,  1],
       [ 4,  5,  3],
       [-2,  0,  0]])

In [79]:
np.linalg.cholesky(S)

array([[ 2.82842712,  0.        ],
       [-0.70710678,  2.12132034]])

In [80]:
np.linalg.qr(S)

(array([[-0.9701425 ,  0.24253563],
        [ 0.24253563,  0.9701425 ]]), array([[-8.24621125,  3.15296313],
        [ 0.        ,  4.36564125]]))

In [81]:
np.linalg.svd(S)

(array([[-0.89442719,  0.4472136 ],
        [ 0.4472136 ,  0.89442719]]),
 array([ 9.,  4.]),
 array([[-0.89442719,  0.4472136 ],
        [ 0.4472136 ,  0.89442719]]))

#### Exemplo de conjunto de dados: obter $\bar{\boldsymbol{X}}$ e $\bar{\boldsymbol{S}}$

In [82]:
X = np.array([[7, 3, 9], [4, 6 ,11], [4, 2, 5], [5, 5, 7]])
print(X)

[[ 7  3  9]
 [ 4  6 11]
 [ 4  2  5]
 [ 5  5  7]]


In [83]:
# vetor de médias
np.mean(X, axis=0)

array([ 5.,  4.,  8.])

In [84]:
# matriz de covariâncias
np.cov(X.T)

array([[ 2.        , -0.66666667,  0.66666667],
       [-0.66666667,  3.33333333,  3.33333333],
       [ 0.66666667,  3.33333333,  6.66666667]])

In [ ]:
s